backend:
  name: github
  repo: akunnaga169/amoreira-lviv-ua
  branch: main
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "post"
    label: "Berita"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Gambar Utama", name: "image", widget: "image", required: false }
      - { label: "Isi Berita", name: "body", widget: "markdown" }